spring:
  application:
    name: ExpenseTracker
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true # Corrected database name
    username: root
    password: joshua6775 # Consider using environment variables for sensitive data in production
  jpa:
    hibernate:
      ddl-auto: update # Or validate, none. 'update' is convenient for development.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false